{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/subtract": {
      "post": {
        "tags": [
          "math-controller"
        ],
        "operationId": "subtract",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MathSolution"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/MathSolution"
                }
              }
            }
          }
        }
      }
    },
    "/multiply": {
      "post": {
        "tags": [
          "math-controller"
        ],
        "operationId": "multiply",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MathSolution"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/MathSolution"
                }
              }
            }
          }
        }
      }
    },
    "/divide": {
      "post": {
        "tags": [
          "math-controller"
        ],
        "operationId": "divide",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MathSolution"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/MathSolution"
                }
              }
            }
          }
        }
      }
    },
    "/add": {
      "post": {
        "tags": [
          "math-controller"
        ],
        "operationId": "add",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MathSolution"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/MathSolution"
                }
              }
            }
          }
        }
      }
    },
    "/randomMonth": {
      "get": {
        "tags": [
          "month-controller"
        ],
        "operationId": "getRandomMonth",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Month"
                }
              }
            }
          }
        }
      }
    },
    "/month/{monthNumber}": {
      "get": {
        "tags": [
          "month-controller"
        ],
        "operationId": "getMonth",
        "parameters": [
          {
            "name": "monthNumber",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Month"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "MathSolution": {
        "type": "object",
        "properties": {
          "operand1": {
            "type": "integer",
            "format": "int32"
          },
          "operand2": {
            "type": "integer",
            "format": "int32"
          },
          "answer": {
            "type": "integer",
            "format": "int32"
          },
          "operation": {
            "type": "string"
          }
        }
      },
      "Month": {
        "type": "object",
        "properties": {
          "number": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string"
          }
        }
      }
    }
  }
}